### ISSUE TITLE
IAM permission error if custom log group is set in CodeBuild config

### ISSUE THREAD

**Issue by mattsb42** [jlhood/github-codebuild-logs#1]
CodeBuild allows for a custom Log Group name to be defined for a Project.

Because the template assumes the default Log Group name of `/aws/codebuild/${ProjectName}` is used, if a custom name was set when configuring the CodeBuild Project, the event processor will throw permissions errors.

One solution to this would be to add an optional parameter that is used, perhaps with a `Condition`, to build the `ProcessBuildEvents` policy.

**Comment by jlhood** [comment]
@mattsb42 Thanks for reporting this. I can add that optional parameter.

**Comment by jlhood** [comment]
PR has been merged. Will be available in v1.1.0, but publishing to SAR is delayed. ETA for the new release is 10/9.

**Comment by jlhood** [comment]
Fixed in v1.1.0 (now released and published to SAR)
