### ISSUE TITLE
Add CodeBuild project name and commit ID to PR statement

### ISSUE THREAD

**Issue by mattsb42** [jlhood/github-codebuild-logs#16]
While debugging an issue with my Windows CI[1], I ran into two issues with keeping track of what was doing what when.

1. I have two CodeBuild projects acting as CI for that repo (Linux and Windows). The CI report contains no indication of which one the report is for. This can make tracking down issues difficult.
1. Windows builds are a lot slower than Linux. :) I ran into one case where I had a syntax issue that also caused my Linux build to fail (commit A). I updated my branch with a fix for this (commit B), and the build for Linux-commit-B actually completed and had a report back in the PR *before* the Windows-commit-A build finished. Fortunately, I could easily tell from the logs that it had the issue from commit A, but if I hadn't known what to look for, it would have been confusing to try to track down the real issue.

[1] https://github.com/mattsb42/pipipxx/pull/17

**Comment by jlhood** [comment]
This feature is available in the latest release (1.2.0).
