### ISSUE TITLE
Change `DeletePreviousComment` to an int

### ISSUE THREAD

**Issue by msaroufim** [jlhood/github-codebuild-logs#35]
### Context
Hi I'm one of the maintainers of torchserve at PyTorch which we comaintain with AWS and we use codebuild and your bot to be able to share with community members issues with their PRs. We can't share the codebuild links directly since they're internal to AWS.

When we run our CI we need to pass on both linux-cpu, linux-gpu and windows so there's a total 3 of comments that need to show and not just 1

https://github.com/pytorch/serve/pulls

### Problem
However often our CI is flaky or it takes a few commits for people to get their PR right so we end up with with dozens of comments from a bot which drown out the useful comments like reviews. And we can't set `DeletePreviousComment` because we need 3 comments to show at a time at a minimum from each of the distributions

### Proposed solution
So if we could instead the number of previous comments to be something like 3 or 6 it makes the discussions on github PRs much more readable.

<img width="103" alt="Screen Shot 2022-02-18 at 2 18 25 PM" src="https://user-images.githubusercontent.com/3282513/154768760-28ccf433-3332-410d-a9c6-5ab2348bce40.png">

**Comment by PatMyron** [comment]
Editing the same comment repeatedly seems better than spamming threads or losing reports:
https://github.com/jlhood/github-codebuild-logs/issues/25#issuecomment-1537283981

**Comment by msaroufim** [comment]
Closing for now since I no longer need this
