### ISSUE TITLE
Deployment fails with "AWS::Events::Rule does not support attribute {Arn}" error

### ISSUE THREAD

**Issue by trivikr** [jlhood/github-codebuild-logs#7]
**Describe the bug**
Deployment of the Serverless Application Repository fails with the following error:
```console
[Error] /Resources/ProcessBuildEventsBuildStatusPermission/Properties/SourceArn/Fn::GetAtt: Resource type AWS::Events::Rule does not support attribute {Arn}. Rollback requested by user.
```

**To Reproduce**
* Visit [Serverless Application Repository](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs) given in README
* Click on "Deploy"
* Enter "CodeBuildProjectName"
* Click on "Deploy"
* Notice that stack fails to get deployed and goes to `ROLLBACK_COMPLETE` state

**Expected behavior**
The Cloudformation stack `serverlessrepo-github-codebuild-logs` gets deployed

**Screenshots**
![Screen Shot 2019-10-03 at 3 50 07 PM](https://user-images.githubusercontent.com/16024985/66169522-873a3d80-e5f5-11e9-9818-0c3d771ec115.png)

**Comment by trivikr** [comment]
I was able to deploy it on my personal account, the error appears on team account where CodeBuild build script is

**Comment by jlhood** [comment]
@trivikr What region were you deploying this in? The error you're pointing out was by resources generated by SAM. It's possible this is a bug in this app, but I'm also concerned, because SAM just had a new release, and I hope this isn't a regression. Can you retry deploying to your personal account and see if you can still successfully deploy it?

**Comment by jlhood** [comment]
Did some more digging. This isn't a SAM issue, but seems like it could be a CloudFormation issue. I've contacted the CloudFormation team to take a look asap.

**Comment by trivikr** [comment]
> What region were you deploying this in?

us-west-2

> Can you retry deploying to your personal account and see if you can still successfully deploy it?

Deletion of Cloudformation stack, and deploy of Serverless Application Repository is successful on my personal account

**Comment by jlhood** [comment]
The CloudFormation issue causing this error has been resolved. You should be able to deploy the app successfully now. Sorry for the inconvenience!

**Comment by trivikr** [comment]
Thank you @jlhood for a quick follow up!
